/**
 *
 *  ConflictResolution.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace project_calendar
{

class ConflictResolution
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _project_id;
        static const std::string _task_id;
        static const std::string _target_user_id;
        static const std::string _kind;
        static const std::string _payload;
        static const std::string _status;
        static const std::string _suggested_by;
        static const std::string _suggested_at;
        static const std::string _decided_by;
        static const std::string _decided_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit ConflictResolution(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit ConflictResolution(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    ConflictResolution(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    ConflictResolution() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column project_id  */
    ///Get the value of the column project_id, returns the default value if the column is null
    const std::string &getValueOfProjectId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProjectId() const noexcept;
    ///Set the value of the column project_id
    void setProjectId(const std::string &pProjectId) noexcept;
    void setProjectId(std::string &&pProjectId) noexcept;

    /**  For column task_id  */
    ///Get the value of the column task_id, returns the default value if the column is null
    const std::string &getValueOfTaskId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTaskId() const noexcept;
    ///Set the value of the column task_id
    void setTaskId(const std::string &pTaskId) noexcept;
    void setTaskId(std::string &&pTaskId) noexcept;

    /**  For column target_user_id  */
    ///Get the value of the column target_user_id, returns the default value if the column is null
    const std::string &getValueOfTargetUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTargetUserId() const noexcept;
    ///Set the value of the column target_user_id
    void setTargetUserId(const std::string &pTargetUserId) noexcept;
    void setTargetUserId(std::string &&pTargetUserId) noexcept;
    void setTargetUserIdToNull() noexcept;

    /**  For column kind  */
    ///Get the value of the column kind, returns the default value if the column is null
    const std::string &getValueOfKind() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getKind() const noexcept;
    ///Set the value of the column kind
    void setKind(const std::string &pKind) noexcept;
    void setKind(std::string &&pKind) noexcept;

    /**  For column payload  */
    ///Get the value of the column payload, returns the default value if the column is null
    const std::string &getValueOfPayload() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPayload() const noexcept;
    ///Set the value of the column payload
    void setPayload(const std::string &pPayload) noexcept;
    void setPayload(std::string &&pPayload) noexcept;

    /**  For column status  */
    ///Get the value of the column status, returns the default value if the column is null
    const std::string &getValueOfStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStatus() const noexcept;
    ///Set the value of the column status
    void setStatus(const std::string &pStatus) noexcept;
    void setStatus(std::string &&pStatus) noexcept;
    void setStatusToNull() noexcept;

    /**  For column suggested_by  */
    ///Get the value of the column suggested_by, returns the default value if the column is null
    const std::string &getValueOfSuggestedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSuggestedBy() const noexcept;
    ///Set the value of the column suggested_by
    void setSuggestedBy(const std::string &pSuggestedBy) noexcept;
    void setSuggestedBy(std::string &&pSuggestedBy) noexcept;
    void setSuggestedByToNull() noexcept;

    /**  For column suggested_at  */
    ///Get the value of the column suggested_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfSuggestedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getSuggestedAt() const noexcept;
    ///Set the value of the column suggested_at
    void setSuggestedAt(const ::trantor::Date &pSuggestedAt) noexcept;
    void setSuggestedAtToNull() noexcept;

    /**  For column decided_by  */
    ///Get the value of the column decided_by, returns the default value if the column is null
    const std::string &getValueOfDecidedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDecidedBy() const noexcept;
    ///Set the value of the column decided_by
    void setDecidedBy(const std::string &pDecidedBy) noexcept;
    void setDecidedBy(std::string &&pDecidedBy) noexcept;
    void setDecidedByToNull() noexcept;

    /**  For column decided_at  */
    ///Get the value of the column decided_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfDecidedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getDecidedAt() const noexcept;
    ///Set the value of the column decided_at
    void setDecidedAt(const ::trantor::Date &pDecidedAt) noexcept;
    void setDecidedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 11;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<ConflictResolution>;
    friend drogon::orm::BaseBuilder<ConflictResolution, true, true>;
    friend drogon::orm::BaseBuilder<ConflictResolution, true, false>;
    friend drogon::orm::BaseBuilder<ConflictResolution, false, true>;
    friend drogon::orm::BaseBuilder<ConflictResolution, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<ConflictResolution>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> projectId_;
    std::shared_ptr<std::string> taskId_;
    std::shared_ptr<std::string> targetUserId_;
    std::shared_ptr<std::string> kind_;
    std::shared_ptr<std::string> payload_;
    std::shared_ptr<std::string> status_;
    std::shared_ptr<std::string> suggestedBy_;
    std::shared_ptr<::trantor::Date> suggestedAt_;
    std::shared_ptr<std::string> decidedBy_;
    std::shared_ptr<::trantor::Date> decidedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[11]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "project_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "task_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "target_user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "kind,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "payload,";
            ++parametersCount;
        }
        sql += "status,";
        ++parametersCount;
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        if(dirtyFlag_[7])
        {
            sql += "suggested_by,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "suggested_at,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "decided_by,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "decided_at,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace project_calendar
} // namespace drogon_model
