/**
 *
 *  AuditLog.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "AuditLog.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::project_calendar;

const std::string AuditLog::Cols::_id = "\"id\"";
const std::string AuditLog::Cols::_timestamp = "\"timestamp\"";
const std::string AuditLog::Cols::_actor_user_id = "\"actor_user_id\"";
const std::string AuditLog::Cols::_action_type = "\"action_type\"";
const std::string AuditLog::Cols::_object_type = "\"object_type\"";
const std::string AuditLog::Cols::_object_id = "\"object_id\"";
const std::string AuditLog::Cols::_project_id = "\"project_id\"";
const std::string AuditLog::Cols::_details = "\"details\"";
const std::string AuditLog::Cols::_ip = "\"ip\"";
const std::string AuditLog::Cols::_user_agent = "\"user_agent\"";
const std::string AuditLog::primaryKeyName = "id";
const bool AuditLog::hasPrimaryKey = true;
const std::string AuditLog::tableName = "\"audit_log\"";

const std::vector<typename AuditLog::MetaData> AuditLog::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"timestamp","::trantor::Date","timestamp with time zone",0,0,0,1},
{"actor_user_id","std::string","uuid",0,0,0,0},
{"action_type","std::string","text",0,0,0,1},
{"object_type","std::string","text",0,0,0,1},
{"object_id","std::string","uuid",0,0,0,0},
{"project_id","std::string","uuid",0,0,0,0},
{"details","std::string","jsonb",0,0,0,0},
{"ip","std::string","inet",0,0,0,0},
{"user_agent","std::string","text",0,0,0,0}
};
const std::string &AuditLog::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
AuditLog::AuditLog(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["timestamp"].isNull())
        {
            auto timeStr = r["timestamp"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["actor_user_id"].isNull())
        {
            actorUserId_=std::make_shared<std::string>(r["actor_user_id"].as<std::string>());
        }
        if(!r["action_type"].isNull())
        {
            actionType_=std::make_shared<std::string>(r["action_type"].as<std::string>());
        }
        if(!r["object_type"].isNull())
        {
            objectType_=std::make_shared<std::string>(r["object_type"].as<std::string>());
        }
        if(!r["object_id"].isNull())
        {
            objectId_=std::make_shared<std::string>(r["object_id"].as<std::string>());
        }
        if(!r["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(r["project_id"].as<std::string>());
        }
        if(!r["details"].isNull())
        {
            details_=std::make_shared<std::string>(r["details"].as<std::string>());
        }
        if(!r["ip"].isNull())
        {
            ip_=std::make_shared<std::string>(r["ip"].as<std::string>());
        }
        if(!r["user_agent"].isNull())
        {
            userAgent_=std::make_shared<std::string>(r["user_agent"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            actorUserId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            actionType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            objectType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            objectId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            projectId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            details_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            ip_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            userAgent_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

AuditLog::AuditLog(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[1]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            actorUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            actionType_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            objectType_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            objectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            details_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            ip_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
}

AuditLog::AuditLog(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("timestamp"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["timestamp"].isNull())
        {
            auto timeStr = pJson["timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("actor_user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["actor_user_id"].isNull())
        {
            actorUserId_=std::make_shared<std::string>(pJson["actor_user_id"].asString());
        }
    }
    if(pJson.isMember("action_type"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["action_type"].isNull())
        {
            actionType_=std::make_shared<std::string>(pJson["action_type"].asString());
        }
    }
    if(pJson.isMember("object_type"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["object_type"].isNull())
        {
            objectType_=std::make_shared<std::string>(pJson["object_type"].asString());
        }
    }
    if(pJson.isMember("object_id"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["object_id"].isNull())
        {
            objectId_=std::make_shared<std::string>(pJson["object_id"].asString());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
    if(pJson.isMember("details"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["details"].isNull())
        {
            details_=std::make_shared<std::string>(pJson["details"].asString());
        }
    }
    if(pJson.isMember("ip"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["ip"].isNull())
        {
            ip_=std::make_shared<std::string>(pJson["ip"].asString());
        }
    }
    if(pJson.isMember("user_agent"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["user_agent"].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson["user_agent"].asString());
        }
    }
}

void AuditLog::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[1]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            actorUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            actionType_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            objectType_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            objectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            details_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            ip_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
}

void AuditLog::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("timestamp"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["timestamp"].isNull())
        {
            auto timeStr = pJson["timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("actor_user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["actor_user_id"].isNull())
        {
            actorUserId_=std::make_shared<std::string>(pJson["actor_user_id"].asString());
        }
    }
    if(pJson.isMember("action_type"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["action_type"].isNull())
        {
            actionType_=std::make_shared<std::string>(pJson["action_type"].asString());
        }
    }
    if(pJson.isMember("object_type"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["object_type"].isNull())
        {
            objectType_=std::make_shared<std::string>(pJson["object_type"].asString());
        }
    }
    if(pJson.isMember("object_id"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["object_id"].isNull())
        {
            objectId_=std::make_shared<std::string>(pJson["object_id"].asString());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
    if(pJson.isMember("details"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["details"].isNull())
        {
            details_=std::make_shared<std::string>(pJson["details"].asString());
        }
    }
    if(pJson.isMember("ip"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["ip"].isNull())
        {
            ip_=std::make_shared<std::string>(pJson["ip"].asString());
        }
    }
    if(pJson.isMember("user_agent"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["user_agent"].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson["user_agent"].asString());
        }
    }
}

const std::string &AuditLog::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLog::getId() const noexcept
{
    return id_;
}
void AuditLog::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void AuditLog::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename AuditLog::PrimaryKeyType & AuditLog::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const ::trantor::Date &AuditLog::getValueOfTimestamp() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(timestamp_)
        return *timestamp_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &AuditLog::getTimestamp() const noexcept
{
    return timestamp_;
}
void AuditLog::setTimestamp(const ::trantor::Date &pTimestamp) noexcept
{
    timestamp_ = std::make_shared<::trantor::Date>(pTimestamp);
    dirtyFlag_[1] = true;
}

const std::string &AuditLog::getValueOfActorUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(actorUserId_)
        return *actorUserId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLog::getActorUserId() const noexcept
{
    return actorUserId_;
}
void AuditLog::setActorUserId(const std::string &pActorUserId) noexcept
{
    actorUserId_ = std::make_shared<std::string>(pActorUserId);
    dirtyFlag_[2] = true;
}
void AuditLog::setActorUserId(std::string &&pActorUserId) noexcept
{
    actorUserId_ = std::make_shared<std::string>(std::move(pActorUserId));
    dirtyFlag_[2] = true;
}
void AuditLog::setActorUserIdToNull() noexcept
{
    actorUserId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &AuditLog::getValueOfActionType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(actionType_)
        return *actionType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLog::getActionType() const noexcept
{
    return actionType_;
}
void AuditLog::setActionType(const std::string &pActionType) noexcept
{
    actionType_ = std::make_shared<std::string>(pActionType);
    dirtyFlag_[3] = true;
}
void AuditLog::setActionType(std::string &&pActionType) noexcept
{
    actionType_ = std::make_shared<std::string>(std::move(pActionType));
    dirtyFlag_[3] = true;
}

const std::string &AuditLog::getValueOfObjectType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(objectType_)
        return *objectType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLog::getObjectType() const noexcept
{
    return objectType_;
}
void AuditLog::setObjectType(const std::string &pObjectType) noexcept
{
    objectType_ = std::make_shared<std::string>(pObjectType);
    dirtyFlag_[4] = true;
}
void AuditLog::setObjectType(std::string &&pObjectType) noexcept
{
    objectType_ = std::make_shared<std::string>(std::move(pObjectType));
    dirtyFlag_[4] = true;
}

const std::string &AuditLog::getValueOfObjectId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(objectId_)
        return *objectId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLog::getObjectId() const noexcept
{
    return objectId_;
}
void AuditLog::setObjectId(const std::string &pObjectId) noexcept
{
    objectId_ = std::make_shared<std::string>(pObjectId);
    dirtyFlag_[5] = true;
}
void AuditLog::setObjectId(std::string &&pObjectId) noexcept
{
    objectId_ = std::make_shared<std::string>(std::move(pObjectId));
    dirtyFlag_[5] = true;
}
void AuditLog::setObjectIdToNull() noexcept
{
    objectId_.reset();
    dirtyFlag_[5] = true;
}

const std::string &AuditLog::getValueOfProjectId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(projectId_)
        return *projectId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLog::getProjectId() const noexcept
{
    return projectId_;
}
void AuditLog::setProjectId(const std::string &pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(pProjectId);
    dirtyFlag_[6] = true;
}
void AuditLog::setProjectId(std::string &&pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(std::move(pProjectId));
    dirtyFlag_[6] = true;
}
void AuditLog::setProjectIdToNull() noexcept
{
    projectId_.reset();
    dirtyFlag_[6] = true;
}

const std::string &AuditLog::getValueOfDetails() const noexcept
{
    static const std::string defaultValue = std::string();
    if(details_)
        return *details_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLog::getDetails() const noexcept
{
    return details_;
}
void AuditLog::setDetails(const std::string &pDetails) noexcept
{
    details_ = std::make_shared<std::string>(pDetails);
    dirtyFlag_[7] = true;
}
void AuditLog::setDetails(std::string &&pDetails) noexcept
{
    details_ = std::make_shared<std::string>(std::move(pDetails));
    dirtyFlag_[7] = true;
}
void AuditLog::setDetailsToNull() noexcept
{
    details_.reset();
    dirtyFlag_[7] = true;
}

const std::string &AuditLog::getValueOfIp() const noexcept
{
    static const std::string defaultValue = std::string();
    if(ip_)
        return *ip_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLog::getIp() const noexcept
{
    return ip_;
}
void AuditLog::setIp(const std::string &pIp) noexcept
{
    ip_ = std::make_shared<std::string>(pIp);
    dirtyFlag_[8] = true;
}
void AuditLog::setIp(std::string &&pIp) noexcept
{
    ip_ = std::make_shared<std::string>(std::move(pIp));
    dirtyFlag_[8] = true;
}
void AuditLog::setIpToNull() noexcept
{
    ip_.reset();
    dirtyFlag_[8] = true;
}

const std::string &AuditLog::getValueOfUserAgent() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userAgent_)
        return *userAgent_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLog::getUserAgent() const noexcept
{
    return userAgent_;
}
void AuditLog::setUserAgent(const std::string &pUserAgent) noexcept
{
    userAgent_ = std::make_shared<std::string>(pUserAgent);
    dirtyFlag_[9] = true;
}
void AuditLog::setUserAgent(std::string &&pUserAgent) noexcept
{
    userAgent_ = std::make_shared<std::string>(std::move(pUserAgent));
    dirtyFlag_[9] = true;
}
void AuditLog::setUserAgentToNull() noexcept
{
    userAgent_.reset();
    dirtyFlag_[9] = true;
}

void AuditLog::updateId(const uint64_t id)
{
}

const std::vector<std::string> &AuditLog::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "timestamp",
        "actor_user_id",
        "action_type",
        "object_type",
        "object_id",
        "project_id",
        "details",
        "ip",
        "user_agent"
    };
    return inCols;
}

void AuditLog::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTimestamp())
        {
            binder << getValueOfTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getActorUserId())
        {
            binder << getValueOfActorUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getActionType())
        {
            binder << getValueOfActionType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getObjectType())
        {
            binder << getValueOfObjectType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getObjectId())
        {
            binder << getValueOfObjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDetails())
        {
            binder << getValueOfDetails();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIp())
        {
            binder << getValueOfIp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUserAgent())
        {
            binder << getValueOfUserAgent();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> AuditLog::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void AuditLog::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTimestamp())
        {
            binder << getValueOfTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getActorUserId())
        {
            binder << getValueOfActorUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getActionType())
        {
            binder << getValueOfActionType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getObjectType())
        {
            binder << getValueOfObjectType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getObjectId())
        {
            binder << getValueOfObjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDetails())
        {
            binder << getValueOfDetails();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIp())
        {
            binder << getValueOfIp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUserAgent())
        {
            binder << getValueOfUserAgent();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value AuditLog::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTimestamp())
    {
        ret["timestamp"]=getTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["timestamp"]=Json::Value();
    }
    if(getActorUserId())
    {
        ret["actor_user_id"]=getValueOfActorUserId();
    }
    else
    {
        ret["actor_user_id"]=Json::Value();
    }
    if(getActionType())
    {
        ret["action_type"]=getValueOfActionType();
    }
    else
    {
        ret["action_type"]=Json::Value();
    }
    if(getObjectType())
    {
        ret["object_type"]=getValueOfObjectType();
    }
    else
    {
        ret["object_type"]=Json::Value();
    }
    if(getObjectId())
    {
        ret["object_id"]=getValueOfObjectId();
    }
    else
    {
        ret["object_id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getDetails())
    {
        ret["details"]=getValueOfDetails();
    }
    else
    {
        ret["details"]=Json::Value();
    }
    if(getIp())
    {
        ret["ip"]=getValueOfIp();
    }
    else
    {
        ret["ip"]=Json::Value();
    }
    if(getUserAgent())
    {
        ret["user_agent"]=getValueOfUserAgent();
    }
    else
    {
        ret["user_agent"]=Json::Value();
    }
    return ret;
}

Json::Value AuditLog::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTimestamp())
            {
                ret[pMasqueradingVector[1]]=getTimestamp()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getActorUserId())
            {
                ret[pMasqueradingVector[2]]=getValueOfActorUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getActionType())
            {
                ret[pMasqueradingVector[3]]=getValueOfActionType();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getObjectType())
            {
                ret[pMasqueradingVector[4]]=getValueOfObjectType();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getObjectId())
            {
                ret[pMasqueradingVector[5]]=getValueOfObjectId();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getProjectId())
            {
                ret[pMasqueradingVector[6]]=getValueOfProjectId();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getDetails())
            {
                ret[pMasqueradingVector[7]]=getValueOfDetails();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getIp())
            {
                ret[pMasqueradingVector[8]]=getValueOfIp();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getUserAgent())
            {
                ret[pMasqueradingVector[9]]=getValueOfUserAgent();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTimestamp())
    {
        ret["timestamp"]=getTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["timestamp"]=Json::Value();
    }
    if(getActorUserId())
    {
        ret["actor_user_id"]=getValueOfActorUserId();
    }
    else
    {
        ret["actor_user_id"]=Json::Value();
    }
    if(getActionType())
    {
        ret["action_type"]=getValueOfActionType();
    }
    else
    {
        ret["action_type"]=Json::Value();
    }
    if(getObjectType())
    {
        ret["object_type"]=getValueOfObjectType();
    }
    else
    {
        ret["object_type"]=Json::Value();
    }
    if(getObjectId())
    {
        ret["object_id"]=getValueOfObjectId();
    }
    else
    {
        ret["object_id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getDetails())
    {
        ret["details"]=getValueOfDetails();
    }
    else
    {
        ret["details"]=Json::Value();
    }
    if(getIp())
    {
        ret["ip"]=getValueOfIp();
    }
    else
    {
        ret["ip"]=Json::Value();
    }
    if(getUserAgent())
    {
        ret["user_agent"]=getValueOfUserAgent();
    }
    else
    {
        ret["user_agent"]=Json::Value();
    }
    return ret;
}

bool AuditLog::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("timestamp"))
    {
        if(!validJsonOfField(1, "timestamp", pJson["timestamp"], err, true))
            return false;
    }
    if(pJson.isMember("actor_user_id"))
    {
        if(!validJsonOfField(2, "actor_user_id", pJson["actor_user_id"], err, true))
            return false;
    }
    if(pJson.isMember("action_type"))
    {
        if(!validJsonOfField(3, "action_type", pJson["action_type"], err, true))
            return false;
    }
    else
    {
        err="The action_type column cannot be null";
        return false;
    }
    if(pJson.isMember("object_type"))
    {
        if(!validJsonOfField(4, "object_type", pJson["object_type"], err, true))
            return false;
    }
    else
    {
        err="The object_type column cannot be null";
        return false;
    }
    if(pJson.isMember("object_id"))
    {
        if(!validJsonOfField(5, "object_id", pJson["object_id"], err, true))
            return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(6, "project_id", pJson["project_id"], err, true))
            return false;
    }
    if(pJson.isMember("details"))
    {
        if(!validJsonOfField(7, "details", pJson["details"], err, true))
            return false;
    }
    if(pJson.isMember("ip"))
    {
        if(!validJsonOfField(8, "ip", pJson["ip"], err, true))
            return false;
    }
    if(pJson.isMember("user_agent"))
    {
        if(!validJsonOfField(9, "user_agent", pJson["user_agent"], err, true))
            return false;
    }
    return true;
}
bool AuditLog::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuditLog::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("timestamp"))
    {
        if(!validJsonOfField(1, "timestamp", pJson["timestamp"], err, false))
            return false;
    }
    if(pJson.isMember("actor_user_id"))
    {
        if(!validJsonOfField(2, "actor_user_id", pJson["actor_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("action_type"))
    {
        if(!validJsonOfField(3, "action_type", pJson["action_type"], err, false))
            return false;
    }
    if(pJson.isMember("object_type"))
    {
        if(!validJsonOfField(4, "object_type", pJson["object_type"], err, false))
            return false;
    }
    if(pJson.isMember("object_id"))
    {
        if(!validJsonOfField(5, "object_id", pJson["object_id"], err, false))
            return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(6, "project_id", pJson["project_id"], err, false))
            return false;
    }
    if(pJson.isMember("details"))
    {
        if(!validJsonOfField(7, "details", pJson["details"], err, false))
            return false;
    }
    if(pJson.isMember("ip"))
    {
        if(!validJsonOfField(8, "ip", pJson["ip"], err, false))
            return false;
    }
    if(pJson.isMember("user_agent"))
    {
        if(!validJsonOfField(9, "user_agent", pJson["user_agent"], err, false))
            return false;
    }
    return true;
}
bool AuditLog::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuditLog::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
