/**
 *
 *  ConflictResolution.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/ConflictResolution.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::project_calendar;

const std::string ConflictResolution::Cols::_id = "\"id\"";
const std::string ConflictResolution::Cols::_project_id = "\"project_id\"";
const std::string ConflictResolution::Cols::_task_id = "\"task_id\"";
const std::string ConflictResolution::Cols::_target_user_id = "\"target_user_id\"";
const std::string ConflictResolution::Cols::_kind = "\"kind\"";
const std::string ConflictResolution::Cols::_payload = "\"payload\"";
const std::string ConflictResolution::Cols::_status = "\"status\"";
const std::string ConflictResolution::Cols::_suggested_by = "\"suggested_by\"";
const std::string ConflictResolution::Cols::_suggested_at = "\"suggested_at\"";
const std::string ConflictResolution::Cols::_decided_by = "\"decided_by\"";
const std::string ConflictResolution::Cols::_decided_at = "\"decided_at\"";
const std::string ConflictResolution::primaryKeyName = "id";
const bool ConflictResolution::hasPrimaryKey = true;
const std::string ConflictResolution::tableName = "\"conflict_resolution\"";

const std::vector<typename ConflictResolution::MetaData> ConflictResolution::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"project_id","std::string","uuid",0,0,0,1},
{"task_id","std::string","uuid",0,0,0,1},
{"target_user_id","std::string","uuid",0,0,0,0},
{"kind","std::string","USER-DEFINED",0,0,0,1},
{"payload","std::string","jsonb",0,0,0,1},
{"status","std::string","USER-DEFINED",0,0,0,0},
{"suggested_by","std::string","uuid",0,0,0,0},
{"suggested_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"decided_by","std::string","uuid",0,0,0,0},
{"decided_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &ConflictResolution::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ConflictResolution::ConflictResolution(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(r["project_id"].as<std::string>());
        }
        if(!r["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(r["task_id"].as<std::string>());
        }
        if(!r["target_user_id"].isNull())
        {
            targetUserId_=std::make_shared<std::string>(r["target_user_id"].as<std::string>());
        }
        if(!r["kind"].isNull())
        {
            kind_=std::make_shared<std::string>(r["kind"].as<std::string>());
        }
        if(!r["payload"].isNull())
        {
            payload_=std::make_shared<std::string>(r["payload"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["suggested_by"].isNull())
        {
            suggestedBy_=std::make_shared<std::string>(r["suggested_by"].as<std::string>());
        }
        if(!r["suggested_at"].isNull())
        {
            auto timeStr = r["suggested_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                suggestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["decided_by"].isNull())
        {
            decidedBy_=std::make_shared<std::string>(r["decided_by"].as<std::string>());
        }
        if(!r["decided_at"].isNull())
        {
            auto timeStr = r["decided_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 11 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            projectId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            taskId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            targetUserId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            kind_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            payload_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            suggestedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                suggestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            decidedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

ConflictResolution::ConflictResolution(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            targetUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            kind_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            payload_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            suggestedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                suggestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            decidedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

ConflictResolution::ConflictResolution(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
    if(pJson.isMember("task_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson["task_id"].asString());
        }
    }
    if(pJson.isMember("target_user_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["target_user_id"].isNull())
        {
            targetUserId_=std::make_shared<std::string>(pJson["target_user_id"].asString());
        }
    }
    if(pJson.isMember("kind"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["kind"].isNull())
        {
            kind_=std::make_shared<std::string>(pJson["kind"].asString());
        }
    }
    if(pJson.isMember("payload"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["payload"].isNull())
        {
            payload_=std::make_shared<std::string>(pJson["payload"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("suggested_by"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["suggested_by"].isNull())
        {
            suggestedBy_=std::make_shared<std::string>(pJson["suggested_by"].asString());
        }
    }
    if(pJson.isMember("suggested_at"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["suggested_at"].isNull())
        {
            auto timeStr = pJson["suggested_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                suggestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("decided_by"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["decided_by"].isNull())
        {
            decidedBy_=std::make_shared<std::string>(pJson["decided_by"].asString());
        }
    }
    if(pJson.isMember("decided_at"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["decided_at"].isNull())
        {
            auto timeStr = pJson["decided_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ConflictResolution::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            targetUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            kind_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            payload_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            suggestedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                suggestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            decidedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ConflictResolution::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
    if(pJson.isMember("task_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson["task_id"].asString());
        }
    }
    if(pJson.isMember("target_user_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["target_user_id"].isNull())
        {
            targetUserId_=std::make_shared<std::string>(pJson["target_user_id"].asString());
        }
    }
    if(pJson.isMember("kind"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["kind"].isNull())
        {
            kind_=std::make_shared<std::string>(pJson["kind"].asString());
        }
    }
    if(pJson.isMember("payload"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["payload"].isNull())
        {
            payload_=std::make_shared<std::string>(pJson["payload"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("suggested_by"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["suggested_by"].isNull())
        {
            suggestedBy_=std::make_shared<std::string>(pJson["suggested_by"].asString());
        }
    }
    if(pJson.isMember("suggested_at"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["suggested_at"].isNull())
        {
            auto timeStr = pJson["suggested_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                suggestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("decided_by"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["decided_by"].isNull())
        {
            decidedBy_=std::make_shared<std::string>(pJson["decided_by"].asString());
        }
    }
    if(pJson.isMember("decided_at"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["decided_at"].isNull())
        {
            auto timeStr = pJson["decided_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &ConflictResolution::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ConflictResolution::getId() const noexcept
{
    return id_;
}
void ConflictResolution::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void ConflictResolution::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename ConflictResolution::PrimaryKeyType & ConflictResolution::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &ConflictResolution::getValueOfProjectId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(projectId_)
        return *projectId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ConflictResolution::getProjectId() const noexcept
{
    return projectId_;
}
void ConflictResolution::setProjectId(const std::string &pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(pProjectId);
    dirtyFlag_[1] = true;
}
void ConflictResolution::setProjectId(std::string &&pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(std::move(pProjectId));
    dirtyFlag_[1] = true;
}

const std::string &ConflictResolution::getValueOfTaskId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(taskId_)
        return *taskId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ConflictResolution::getTaskId() const noexcept
{
    return taskId_;
}
void ConflictResolution::setTaskId(const std::string &pTaskId) noexcept
{
    taskId_ = std::make_shared<std::string>(pTaskId);
    dirtyFlag_[2] = true;
}
void ConflictResolution::setTaskId(std::string &&pTaskId) noexcept
{
    taskId_ = std::make_shared<std::string>(std::move(pTaskId));
    dirtyFlag_[2] = true;
}

const std::string &ConflictResolution::getValueOfTargetUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(targetUserId_)
        return *targetUserId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ConflictResolution::getTargetUserId() const noexcept
{
    return targetUserId_;
}
void ConflictResolution::setTargetUserId(const std::string &pTargetUserId) noexcept
{
    targetUserId_ = std::make_shared<std::string>(pTargetUserId);
    dirtyFlag_[3] = true;
}
void ConflictResolution::setTargetUserId(std::string &&pTargetUserId) noexcept
{
    targetUserId_ = std::make_shared<std::string>(std::move(pTargetUserId));
    dirtyFlag_[3] = true;
}
void ConflictResolution::setTargetUserIdToNull() noexcept
{
    targetUserId_.reset();
    dirtyFlag_[3] = true;
}

const std::string &ConflictResolution::getValueOfKind() const noexcept
{
    static const std::string defaultValue = std::string();
    if(kind_)
        return *kind_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ConflictResolution::getKind() const noexcept
{
    return kind_;
}
void ConflictResolution::setKind(const std::string &pKind) noexcept
{
    kind_ = std::make_shared<std::string>(pKind);
    dirtyFlag_[4] = true;
}
void ConflictResolution::setKind(std::string &&pKind) noexcept
{
    kind_ = std::make_shared<std::string>(std::move(pKind));
    dirtyFlag_[4] = true;
}

const std::string &ConflictResolution::getValueOfPayload() const noexcept
{
    static const std::string defaultValue = std::string();
    if(payload_)
        return *payload_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ConflictResolution::getPayload() const noexcept
{
    return payload_;
}
void ConflictResolution::setPayload(const std::string &pPayload) noexcept
{
    payload_ = std::make_shared<std::string>(pPayload);
    dirtyFlag_[5] = true;
}
void ConflictResolution::setPayload(std::string &&pPayload) noexcept
{
    payload_ = std::make_shared<std::string>(std::move(pPayload));
    dirtyFlag_[5] = true;
}

const std::string &ConflictResolution::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ConflictResolution::getStatus() const noexcept
{
    return status_;
}
void ConflictResolution::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[6] = true;
}
void ConflictResolution::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[6] = true;
}
void ConflictResolution::setStatusToNull() noexcept
{
    status_.reset();
    dirtyFlag_[6] = true;
}

const std::string &ConflictResolution::getValueOfSuggestedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(suggestedBy_)
        return *suggestedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ConflictResolution::getSuggestedBy() const noexcept
{
    return suggestedBy_;
}
void ConflictResolution::setSuggestedBy(const std::string &pSuggestedBy) noexcept
{
    suggestedBy_ = std::make_shared<std::string>(pSuggestedBy);
    dirtyFlag_[7] = true;
}
void ConflictResolution::setSuggestedBy(std::string &&pSuggestedBy) noexcept
{
    suggestedBy_ = std::make_shared<std::string>(std::move(pSuggestedBy));
    dirtyFlag_[7] = true;
}
void ConflictResolution::setSuggestedByToNull() noexcept
{
    suggestedBy_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &ConflictResolution::getValueOfSuggestedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(suggestedAt_)
        return *suggestedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ConflictResolution::getSuggestedAt() const noexcept
{
    return suggestedAt_;
}
void ConflictResolution::setSuggestedAt(const ::trantor::Date &pSuggestedAt) noexcept
{
    suggestedAt_ = std::make_shared<::trantor::Date>(pSuggestedAt);
    dirtyFlag_[8] = true;
}
void ConflictResolution::setSuggestedAtToNull() noexcept
{
    suggestedAt_.reset();
    dirtyFlag_[8] = true;
}

const std::string &ConflictResolution::getValueOfDecidedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(decidedBy_)
        return *decidedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ConflictResolution::getDecidedBy() const noexcept
{
    return decidedBy_;
}
void ConflictResolution::setDecidedBy(const std::string &pDecidedBy) noexcept
{
    decidedBy_ = std::make_shared<std::string>(pDecidedBy);
    dirtyFlag_[9] = true;
}
void ConflictResolution::setDecidedBy(std::string &&pDecidedBy) noexcept
{
    decidedBy_ = std::make_shared<std::string>(std::move(pDecidedBy));
    dirtyFlag_[9] = true;
}
void ConflictResolution::setDecidedByToNull() noexcept
{
    decidedBy_.reset();
    dirtyFlag_[9] = true;
}

const ::trantor::Date &ConflictResolution::getValueOfDecidedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(decidedAt_)
        return *decidedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ConflictResolution::getDecidedAt() const noexcept
{
    return decidedAt_;
}
void ConflictResolution::setDecidedAt(const ::trantor::Date &pDecidedAt) noexcept
{
    decidedAt_ = std::make_shared<::trantor::Date>(pDecidedAt);
    dirtyFlag_[10] = true;
}
void ConflictResolution::setDecidedAtToNull() noexcept
{
    decidedAt_.reset();
    dirtyFlag_[10] = true;
}

void ConflictResolution::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ConflictResolution::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "project_id",
        "task_id",
        "target_user_id",
        "kind",
        "payload",
        "status",
        "suggested_by",
        "suggested_at",
        "decided_by",
        "decided_at"
    };
    return inCols;
}

void ConflictResolution::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTaskId())
        {
            binder << getValueOfTaskId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTargetUserId())
        {
            binder << getValueOfTargetUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getKind())
        {
            binder << getValueOfKind();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getPayload())
        {
            binder << getValueOfPayload();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSuggestedBy())
        {
            binder << getValueOfSuggestedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getSuggestedAt())
        {
            binder << getValueOfSuggestedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getDecidedBy())
        {
            binder << getValueOfDecidedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getDecidedAt())
        {
            binder << getValueOfDecidedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ConflictResolution::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void ConflictResolution::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTaskId())
        {
            binder << getValueOfTaskId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTargetUserId())
        {
            binder << getValueOfTargetUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getKind())
        {
            binder << getValueOfKind();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getPayload())
        {
            binder << getValueOfPayload();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSuggestedBy())
        {
            binder << getValueOfSuggestedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getSuggestedAt())
        {
            binder << getValueOfSuggestedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getDecidedBy())
        {
            binder << getValueOfDecidedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getDecidedAt())
        {
            binder << getValueOfDecidedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ConflictResolution::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getTaskId())
    {
        ret["task_id"]=getValueOfTaskId();
    }
    else
    {
        ret["task_id"]=Json::Value();
    }
    if(getTargetUserId())
    {
        ret["target_user_id"]=getValueOfTargetUserId();
    }
    else
    {
        ret["target_user_id"]=Json::Value();
    }
    if(getKind())
    {
        ret["kind"]=getValueOfKind();
    }
    else
    {
        ret["kind"]=Json::Value();
    }
    if(getPayload())
    {
        ret["payload"]=getValueOfPayload();
    }
    else
    {
        ret["payload"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getSuggestedBy())
    {
        ret["suggested_by"]=getValueOfSuggestedBy();
    }
    else
    {
        ret["suggested_by"]=Json::Value();
    }
    if(getSuggestedAt())
    {
        ret["suggested_at"]=getSuggestedAt()->toDbStringLocal();
    }
    else
    {
        ret["suggested_at"]=Json::Value();
    }
    if(getDecidedBy())
    {
        ret["decided_by"]=getValueOfDecidedBy();
    }
    else
    {
        ret["decided_by"]=Json::Value();
    }
    if(getDecidedAt())
    {
        ret["decided_at"]=getDecidedAt()->toDbStringLocal();
    }
    else
    {
        ret["decided_at"]=Json::Value();
    }
    return ret;
}

Json::Value ConflictResolution::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 11)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getProjectId())
            {
                ret[pMasqueradingVector[1]]=getValueOfProjectId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTaskId())
            {
                ret[pMasqueradingVector[2]]=getValueOfTaskId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getTargetUserId())
            {
                ret[pMasqueradingVector[3]]=getValueOfTargetUserId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getKind())
            {
                ret[pMasqueradingVector[4]]=getValueOfKind();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getPayload())
            {
                ret[pMasqueradingVector[5]]=getValueOfPayload();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[6]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getSuggestedBy())
            {
                ret[pMasqueradingVector[7]]=getValueOfSuggestedBy();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getSuggestedAt())
            {
                ret[pMasqueradingVector[8]]=getSuggestedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getDecidedBy())
            {
                ret[pMasqueradingVector[9]]=getValueOfDecidedBy();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getDecidedAt())
            {
                ret[pMasqueradingVector[10]]=getDecidedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getTaskId())
    {
        ret["task_id"]=getValueOfTaskId();
    }
    else
    {
        ret["task_id"]=Json::Value();
    }
    if(getTargetUserId())
    {
        ret["target_user_id"]=getValueOfTargetUserId();
    }
    else
    {
        ret["target_user_id"]=Json::Value();
    }
    if(getKind())
    {
        ret["kind"]=getValueOfKind();
    }
    else
    {
        ret["kind"]=Json::Value();
    }
    if(getPayload())
    {
        ret["payload"]=getValueOfPayload();
    }
    else
    {
        ret["payload"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getSuggestedBy())
    {
        ret["suggested_by"]=getValueOfSuggestedBy();
    }
    else
    {
        ret["suggested_by"]=Json::Value();
    }
    if(getSuggestedAt())
    {
        ret["suggested_at"]=getSuggestedAt()->toDbStringLocal();
    }
    else
    {
        ret["suggested_at"]=Json::Value();
    }
    if(getDecidedBy())
    {
        ret["decided_by"]=getValueOfDecidedBy();
    }
    else
    {
        ret["decided_by"]=Json::Value();
    }
    if(getDecidedAt())
    {
        ret["decided_at"]=getDecidedAt()->toDbStringLocal();
    }
    else
    {
        ret["decided_at"]=Json::Value();
    }
    return ret;
}

bool ConflictResolution::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(1, "project_id", pJson["project_id"], err, true))
            return false;
    }
    else
    {
        err="The project_id column cannot be null";
        return false;
    }
    if(pJson.isMember("task_id"))
    {
        if(!validJsonOfField(2, "task_id", pJson["task_id"], err, true))
            return false;
    }
    else
    {
        err="The task_id column cannot be null";
        return false;
    }
    if(pJson.isMember("target_user_id"))
    {
        if(!validJsonOfField(3, "target_user_id", pJson["target_user_id"], err, true))
            return false;
    }
    if(pJson.isMember("kind"))
    {
        if(!validJsonOfField(4, "kind", pJson["kind"], err, true))
            return false;
    }
    else
    {
        err="The kind column cannot be null";
        return false;
    }
    if(pJson.isMember("payload"))
    {
        if(!validJsonOfField(5, "payload", pJson["payload"], err, true))
            return false;
    }
    else
    {
        err="The payload column cannot be null";
        return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(6, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("suggested_by"))
    {
        if(!validJsonOfField(7, "suggested_by", pJson["suggested_by"], err, true))
            return false;
    }
    if(pJson.isMember("suggested_at"))
    {
        if(!validJsonOfField(8, "suggested_at", pJson["suggested_at"], err, true))
            return false;
    }
    if(pJson.isMember("decided_by"))
    {
        if(!validJsonOfField(9, "decided_by", pJson["decided_by"], err, true))
            return false;
    }
    if(pJson.isMember("decided_at"))
    {
        if(!validJsonOfField(10, "decided_at", pJson["decided_at"], err, true))
            return false;
    }
    return true;
}
bool ConflictResolution::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ConflictResolution::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(1, "project_id", pJson["project_id"], err, false))
            return false;
    }
    if(pJson.isMember("task_id"))
    {
        if(!validJsonOfField(2, "task_id", pJson["task_id"], err, false))
            return false;
    }
    if(pJson.isMember("target_user_id"))
    {
        if(!validJsonOfField(3, "target_user_id", pJson["target_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("kind"))
    {
        if(!validJsonOfField(4, "kind", pJson["kind"], err, false))
            return false;
    }
    if(pJson.isMember("payload"))
    {
        if(!validJsonOfField(5, "payload", pJson["payload"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(6, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("suggested_by"))
    {
        if(!validJsonOfField(7, "suggested_by", pJson["suggested_by"], err, false))
            return false;
    }
    if(pJson.isMember("suggested_at"))
    {
        if(!validJsonOfField(8, "suggested_at", pJson["suggested_at"], err, false))
            return false;
    }
    if(pJson.isMember("decided_by"))
    {
        if(!validJsonOfField(9, "decided_by", pJson["decided_by"], err, false))
            return false;
    }
    if(pJson.isMember("decided_at"))
    {
        if(!validJsonOfField(10, "decided_at", pJson["decided_at"], err, false))
            return false;
    }
    return true;
}
bool ConflictResolution::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ConflictResolution::validJsonOfField(size_t index,
                                          const std::string &fieldName,
                                          const Json::Value &pJson,
                                          std::string &err,
                                          bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
