/**
 *
 *  ProjectAllocation.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/ProjectAllocation.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::project_calendar;

const std::string ProjectAllocation::Cols::_id = "\"id\"";
const std::string ProjectAllocation::Cols::_project_id = "\"project_id\"";
const std::string ProjectAllocation::Cols::_user_id = "\"user_id\"";
const std::string ProjectAllocation::Cols::_weekday = "\"weekday\"";
const std::string ProjectAllocation::Cols::_start_time = "\"start_time\"";
const std::string ProjectAllocation::Cols::_end_time = "\"end_time\"";
const std::string ProjectAllocation::Cols::_hours_per_day = "\"hours_per_day\"";
const std::string ProjectAllocation::primaryKeyName = "id";
const bool ProjectAllocation::hasPrimaryKey = true;
const std::string ProjectAllocation::tableName = "\"project_allocation\"";

const std::vector<typename ProjectAllocation::MetaData> ProjectAllocation::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"project_id","std::string","uuid",0,0,0,1},
{"user_id","std::string","uuid",0,0,0,1},
{"weekday","int32_t","integer",4,0,0,0},
{"start_time","std::string","time without time zone",0,0,0,1},
{"end_time","std::string","time without time zone",0,0,0,1},
{"hours_per_day","std::string","numeric",0,0,0,0}
};
const std::string &ProjectAllocation::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ProjectAllocation::ProjectAllocation(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(r["project_id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["weekday"].isNull())
        {
            weekday_=std::make_shared<int32_t>(r["weekday"].as<int32_t>());
        }
        if(!r["start_time"].isNull())
        {
            startTime_=std::make_shared<std::string>(r["start_time"].as<std::string>());
        }
        if(!r["end_time"].isNull())
        {
            endTime_=std::make_shared<std::string>(r["end_time"].as<std::string>());
        }
        if(!r["hours_per_day"].isNull())
        {
            hoursPerDay_=std::make_shared<std::string>(r["hours_per_day"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            projectId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            weekday_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            startTime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            endTime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            hoursPerDay_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

ProjectAllocation::ProjectAllocation(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            weekday_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            startTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            endTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            hoursPerDay_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

ProjectAllocation::ProjectAllocation(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("weekday"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["weekday"].isNull())
        {
            weekday_=std::make_shared<int32_t>((int32_t)pJson["weekday"].asInt64());
        }
    }
    if(pJson.isMember("start_time"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["start_time"].isNull())
        {
            startTime_=std::make_shared<std::string>(pJson["start_time"].asString());
        }
    }
    if(pJson.isMember("end_time"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["end_time"].isNull())
        {
            endTime_=std::make_shared<std::string>(pJson["end_time"].asString());
        }
    }
    if(pJson.isMember("hours_per_day"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["hours_per_day"].isNull())
        {
            hoursPerDay_=std::make_shared<std::string>(pJson["hours_per_day"].asString());
        }
    }
}

void ProjectAllocation::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            weekday_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            startTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            endTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            hoursPerDay_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

void ProjectAllocation::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("weekday"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["weekday"].isNull())
        {
            weekday_=std::make_shared<int32_t>((int32_t)pJson["weekday"].asInt64());
        }
    }
    if(pJson.isMember("start_time"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["start_time"].isNull())
        {
            startTime_=std::make_shared<std::string>(pJson["start_time"].asString());
        }
    }
    if(pJson.isMember("end_time"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["end_time"].isNull())
        {
            endTime_=std::make_shared<std::string>(pJson["end_time"].asString());
        }
    }
    if(pJson.isMember("hours_per_day"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["hours_per_day"].isNull())
        {
            hoursPerDay_=std::make_shared<std::string>(pJson["hours_per_day"].asString());
        }
    }
}

const std::string &ProjectAllocation::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectAllocation::getId() const noexcept
{
    return id_;
}
void ProjectAllocation::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void ProjectAllocation::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename ProjectAllocation::PrimaryKeyType & ProjectAllocation::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &ProjectAllocation::getValueOfProjectId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(projectId_)
        return *projectId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectAllocation::getProjectId() const noexcept
{
    return projectId_;
}
void ProjectAllocation::setProjectId(const std::string &pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(pProjectId);
    dirtyFlag_[1] = true;
}
void ProjectAllocation::setProjectId(std::string &&pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(std::move(pProjectId));
    dirtyFlag_[1] = true;
}

const std::string &ProjectAllocation::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectAllocation::getUserId() const noexcept
{
    return userId_;
}
void ProjectAllocation::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[2] = true;
}
void ProjectAllocation::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[2] = true;
}

const int32_t &ProjectAllocation::getValueOfWeekday() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(weekday_)
        return *weekday_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ProjectAllocation::getWeekday() const noexcept
{
    return weekday_;
}
void ProjectAllocation::setWeekday(const int32_t &pWeekday) noexcept
{
    weekday_ = std::make_shared<int32_t>(pWeekday);
    dirtyFlag_[3] = true;
}
void ProjectAllocation::setWeekdayToNull() noexcept
{
    weekday_.reset();
    dirtyFlag_[3] = true;
}

const std::string &ProjectAllocation::getValueOfStartTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(startTime_)
        return *startTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectAllocation::getStartTime() const noexcept
{
    return startTime_;
}
void ProjectAllocation::setStartTime(const std::string &pStartTime) noexcept
{
    startTime_ = std::make_shared<std::string>(pStartTime);
    dirtyFlag_[4] = true;
}
void ProjectAllocation::setStartTime(std::string &&pStartTime) noexcept
{
    startTime_ = std::make_shared<std::string>(std::move(pStartTime));
    dirtyFlag_[4] = true;
}

const std::string &ProjectAllocation::getValueOfEndTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(endTime_)
        return *endTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectAllocation::getEndTime() const noexcept
{
    return endTime_;
}
void ProjectAllocation::setEndTime(const std::string &pEndTime) noexcept
{
    endTime_ = std::make_shared<std::string>(pEndTime);
    dirtyFlag_[5] = true;
}
void ProjectAllocation::setEndTime(std::string &&pEndTime) noexcept
{
    endTime_ = std::make_shared<std::string>(std::move(pEndTime));
    dirtyFlag_[5] = true;
}

const std::string &ProjectAllocation::getValueOfHoursPerDay() const noexcept
{
    static const std::string defaultValue = std::string();
    if(hoursPerDay_)
        return *hoursPerDay_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectAllocation::getHoursPerDay() const noexcept
{
    return hoursPerDay_;
}
void ProjectAllocation::setHoursPerDay(const std::string &pHoursPerDay) noexcept
{
    hoursPerDay_ = std::make_shared<std::string>(pHoursPerDay);
    dirtyFlag_[6] = true;
}
void ProjectAllocation::setHoursPerDay(std::string &&pHoursPerDay) noexcept
{
    hoursPerDay_ = std::make_shared<std::string>(std::move(pHoursPerDay));
    dirtyFlag_[6] = true;
}
void ProjectAllocation::setHoursPerDayToNull() noexcept
{
    hoursPerDay_.reset();
    dirtyFlag_[6] = true;
}

void ProjectAllocation::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ProjectAllocation::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "project_id",
        "user_id",
        "weekday",
        "start_time",
        "end_time",
        "hours_per_day"
    };
    return inCols;
}

void ProjectAllocation::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getWeekday())
        {
            binder << getValueOfWeekday();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStartTime())
        {
            binder << getValueOfStartTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEndTime())
        {
            binder << getValueOfEndTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getHoursPerDay())
        {
            binder << getValueOfHoursPerDay();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ProjectAllocation::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void ProjectAllocation::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getWeekday())
        {
            binder << getValueOfWeekday();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStartTime())
        {
            binder << getValueOfStartTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEndTime())
        {
            binder << getValueOfEndTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getHoursPerDay())
        {
            binder << getValueOfHoursPerDay();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ProjectAllocation::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getWeekday())
    {
        ret["weekday"]=getValueOfWeekday();
    }
    else
    {
        ret["weekday"]=Json::Value();
    }
    if(getStartTime())
    {
        ret["start_time"]=getValueOfStartTime();
    }
    else
    {
        ret["start_time"]=Json::Value();
    }
    if(getEndTime())
    {
        ret["end_time"]=getValueOfEndTime();
    }
    else
    {
        ret["end_time"]=Json::Value();
    }
    if(getHoursPerDay())
    {
        ret["hours_per_day"]=getValueOfHoursPerDay();
    }
    else
    {
        ret["hours_per_day"]=Json::Value();
    }
    return ret;
}

Json::Value ProjectAllocation::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getProjectId())
            {
                ret[pMasqueradingVector[1]]=getValueOfProjectId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[2]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getWeekday())
            {
                ret[pMasqueradingVector[3]]=getValueOfWeekday();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getStartTime())
            {
                ret[pMasqueradingVector[4]]=getValueOfStartTime();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getEndTime())
            {
                ret[pMasqueradingVector[5]]=getValueOfEndTime();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getHoursPerDay())
            {
                ret[pMasqueradingVector[6]]=getValueOfHoursPerDay();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getWeekday())
    {
        ret["weekday"]=getValueOfWeekday();
    }
    else
    {
        ret["weekday"]=Json::Value();
    }
    if(getStartTime())
    {
        ret["start_time"]=getValueOfStartTime();
    }
    else
    {
        ret["start_time"]=Json::Value();
    }
    if(getEndTime())
    {
        ret["end_time"]=getValueOfEndTime();
    }
    else
    {
        ret["end_time"]=Json::Value();
    }
    if(getHoursPerDay())
    {
        ret["hours_per_day"]=getValueOfHoursPerDay();
    }
    else
    {
        ret["hours_per_day"]=Json::Value();
    }
    return ret;
}

bool ProjectAllocation::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(1, "project_id", pJson["project_id"], err, true))
            return false;
    }
    else
    {
        err="The project_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("weekday"))
    {
        if(!validJsonOfField(3, "weekday", pJson["weekday"], err, true))
            return false;
    }
    if(pJson.isMember("start_time"))
    {
        if(!validJsonOfField(4, "start_time", pJson["start_time"], err, true))
            return false;
    }
    else
    {
        err="The start_time column cannot be null";
        return false;
    }
    if(pJson.isMember("end_time"))
    {
        if(!validJsonOfField(5, "end_time", pJson["end_time"], err, true))
            return false;
    }
    else
    {
        err="The end_time column cannot be null";
        return false;
    }
    if(pJson.isMember("hours_per_day"))
    {
        if(!validJsonOfField(6, "hours_per_day", pJson["hours_per_day"], err, true))
            return false;
    }
    return true;
}
bool ProjectAllocation::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProjectAllocation::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(1, "project_id", pJson["project_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("weekday"))
    {
        if(!validJsonOfField(3, "weekday", pJson["weekday"], err, false))
            return false;
    }
    if(pJson.isMember("start_time"))
    {
        if(!validJsonOfField(4, "start_time", pJson["start_time"], err, false))
            return false;
    }
    if(pJson.isMember("end_time"))
    {
        if(!validJsonOfField(5, "end_time", pJson["end_time"], err, false))
            return false;
    }
    if(pJson.isMember("hours_per_day"))
    {
        if(!validJsonOfField(6, "hours_per_day", pJson["hours_per_day"], err, false))
            return false;
    }
    return true;
}
bool ProjectAllocation::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProjectAllocation::validJsonOfField(size_t index,
                                         const std::string &fieldName,
                                         const Json::Value &pJson,
                                         std::string &err,
                                         bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
