/**
 *
 *  RolePermission.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/RolePermission.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::project_calendar;

const std::string RolePermission::Cols::_id = "\"id\"";
const std::string RolePermission::Cols::_role = "\"role\"";
const std::string RolePermission::Cols::_permission_key = "\"permission_key\"";
const std::string RolePermission::Cols::_is_global = "\"is_global\"";
const std::string RolePermission::primaryKeyName = "id";
const bool RolePermission::hasPrimaryKey = true;
const std::string RolePermission::tableName = "\"role_permission\"";

const std::vector<typename RolePermission::MetaData> RolePermission::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"role","std::string","USER-DEFINED",0,0,0,1},
{"permission_key","std::string","text",0,0,0,1},
{"is_global","bool","boolean",1,0,0,0}
};
const std::string &RolePermission::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
RolePermission::RolePermission(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["role"].isNull())
        {
            role_=std::make_shared<std::string>(r["role"].as<std::string>());
        }
        if(!r["permission_key"].isNull())
        {
            permissionKey_=std::make_shared<std::string>(r["permission_key"].as<std::string>());
        }
        if(!r["is_global"].isNull())
        {
            isGlobal_=std::make_shared<bool>(r["is_global"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            role_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            permissionKey_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            isGlobal_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

RolePermission::RolePermission(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            role_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            permissionKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            isGlobal_=std::make_shared<bool>(pJson[pMasqueradingVector[3]].asBool());
        }
    }
}

RolePermission::RolePermission(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("role"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["role"].isNull())
        {
            role_=std::make_shared<std::string>(pJson["role"].asString());
        }
    }
    if(pJson.isMember("permission_key"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["permission_key"].isNull())
        {
            permissionKey_=std::make_shared<std::string>(pJson["permission_key"].asString());
        }
    }
    if(pJson.isMember("is_global"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["is_global"].isNull())
        {
            isGlobal_=std::make_shared<bool>(pJson["is_global"].asBool());
        }
    }
}

void RolePermission::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            role_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            permissionKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            isGlobal_=std::make_shared<bool>(pJson[pMasqueradingVector[3]].asBool());
        }
    }
}

void RolePermission::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("role"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["role"].isNull())
        {
            role_=std::make_shared<std::string>(pJson["role"].asString());
        }
    }
    if(pJson.isMember("permission_key"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["permission_key"].isNull())
        {
            permissionKey_=std::make_shared<std::string>(pJson["permission_key"].asString());
        }
    }
    if(pJson.isMember("is_global"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["is_global"].isNull())
        {
            isGlobal_=std::make_shared<bool>(pJson["is_global"].asBool());
        }
    }
}

const std::string &RolePermission::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RolePermission::getId() const noexcept
{
    return id_;
}
void RolePermission::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void RolePermission::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename RolePermission::PrimaryKeyType & RolePermission::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &RolePermission::getValueOfRole() const noexcept
{
    static const std::string defaultValue = std::string();
    if(role_)
        return *role_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RolePermission::getRole() const noexcept
{
    return role_;
}
void RolePermission::setRole(const std::string &pRole) noexcept
{
    role_ = std::make_shared<std::string>(pRole);
    dirtyFlag_[1] = true;
}
void RolePermission::setRole(std::string &&pRole) noexcept
{
    role_ = std::make_shared<std::string>(std::move(pRole));
    dirtyFlag_[1] = true;
}

const std::string &RolePermission::getValueOfPermissionKey() const noexcept
{
    static const std::string defaultValue = std::string();
    if(permissionKey_)
        return *permissionKey_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RolePermission::getPermissionKey() const noexcept
{
    return permissionKey_;
}
void RolePermission::setPermissionKey(const std::string &pPermissionKey) noexcept
{
    permissionKey_ = std::make_shared<std::string>(pPermissionKey);
    dirtyFlag_[2] = true;
}
void RolePermission::setPermissionKey(std::string &&pPermissionKey) noexcept
{
    permissionKey_ = std::make_shared<std::string>(std::move(pPermissionKey));
    dirtyFlag_[2] = true;
}

const bool &RolePermission::getValueOfIsGlobal() const noexcept
{
    static const bool defaultValue = bool();
    if(isGlobal_)
        return *isGlobal_;
    return defaultValue;
}
const std::shared_ptr<bool> &RolePermission::getIsGlobal() const noexcept
{
    return isGlobal_;
}
void RolePermission::setIsGlobal(const bool &pIsGlobal) noexcept
{
    isGlobal_ = std::make_shared<bool>(pIsGlobal);
    dirtyFlag_[3] = true;
}
void RolePermission::setIsGlobalToNull() noexcept
{
    isGlobal_.reset();
    dirtyFlag_[3] = true;
}

void RolePermission::updateId(const uint64_t id)
{
}

const std::vector<std::string> &RolePermission::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "role",
        "permission_key",
        "is_global"
    };
    return inCols;
}

void RolePermission::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRole())
        {
            binder << getValueOfRole();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPermissionKey())
        {
            binder << getValueOfPermissionKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getIsGlobal())
        {
            binder << getValueOfIsGlobal();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> RolePermission::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void RolePermission::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRole())
        {
            binder << getValueOfRole();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPermissionKey())
        {
            binder << getValueOfPermissionKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getIsGlobal())
        {
            binder << getValueOfIsGlobal();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value RolePermission::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getRole())
    {
        ret["role"]=getValueOfRole();
    }
    else
    {
        ret["role"]=Json::Value();
    }
    if(getPermissionKey())
    {
        ret["permission_key"]=getValueOfPermissionKey();
    }
    else
    {
        ret["permission_key"]=Json::Value();
    }
    if(getIsGlobal())
    {
        ret["is_global"]=getValueOfIsGlobal();
    }
    else
    {
        ret["is_global"]=Json::Value();
    }
    return ret;
}

Json::Value RolePermission::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getRole())
            {
                ret[pMasqueradingVector[1]]=getValueOfRole();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPermissionKey())
            {
                ret[pMasqueradingVector[2]]=getValueOfPermissionKey();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getIsGlobal())
            {
                ret[pMasqueradingVector[3]]=getValueOfIsGlobal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getRole())
    {
        ret["role"]=getValueOfRole();
    }
    else
    {
        ret["role"]=Json::Value();
    }
    if(getPermissionKey())
    {
        ret["permission_key"]=getValueOfPermissionKey();
    }
    else
    {
        ret["permission_key"]=Json::Value();
    }
    if(getIsGlobal())
    {
        ret["is_global"]=getValueOfIsGlobal();
    }
    else
    {
        ret["is_global"]=Json::Value();
    }
    return ret;
}

bool RolePermission::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("role"))
    {
        if(!validJsonOfField(1, "role", pJson["role"], err, true))
            return false;
    }
    else
    {
        err="The role column cannot be null";
        return false;
    }
    if(pJson.isMember("permission_key"))
    {
        if(!validJsonOfField(2, "permission_key", pJson["permission_key"], err, true))
            return false;
    }
    else
    {
        err="The permission_key column cannot be null";
        return false;
    }
    if(pJson.isMember("is_global"))
    {
        if(!validJsonOfField(3, "is_global", pJson["is_global"], err, true))
            return false;
    }
    return true;
}
bool RolePermission::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool RolePermission::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("role"))
    {
        if(!validJsonOfField(1, "role", pJson["role"], err, false))
            return false;
    }
    if(pJson.isMember("permission_key"))
    {
        if(!validJsonOfField(2, "permission_key", pJson["permission_key"], err, false))
            return false;
    }
    if(pJson.isMember("is_global"))
    {
        if(!validJsonOfField(3, "is_global", pJson["is_global"], err, false))
            return false;
    }
    return true;
}
bool RolePermission::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool RolePermission::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
