/**
 *
 *  TaskDependency.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "models/TaskDependency.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::project_calendar;

const std::string TaskDependency::Cols::_id = "\"id\"";
const std::string TaskDependency::Cols::_task_id = "\"task_id\"";
const std::string TaskDependency::Cols::_depends_on_id = "\"depends_on_id\"";
const std::string TaskDependency::Cols::_kind = "\"kind\"";
const std::string TaskDependency::primaryKeyName = "id";
const bool TaskDependency::hasPrimaryKey = true;
const std::string TaskDependency::tableName = "\"task_dependency\"";

const std::vector<typename TaskDependency::MetaData> TaskDependency::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"task_id","std::string","uuid",0,0,0,1},
{"depends_on_id","std::string","uuid",0,0,0,1},
{"kind","std::string","text",0,0,0,0}
};
const std::string &TaskDependency::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TaskDependency::TaskDependency(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(r["task_id"].as<std::string>());
        }
        if(!r["depends_on_id"].isNull())
        {
            dependsOnId_=std::make_shared<std::string>(r["depends_on_id"].as<std::string>());
        }
        if(!r["kind"].isNull())
        {
            kind_=std::make_shared<std::string>(r["kind"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            taskId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            dependsOnId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            kind_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

TaskDependency::TaskDependency(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dependsOnId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            kind_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

TaskDependency::TaskDependency(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("task_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson["task_id"].asString());
        }
    }
    if(pJson.isMember("depends_on_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["depends_on_id"].isNull())
        {
            dependsOnId_=std::make_shared<std::string>(pJson["depends_on_id"].asString());
        }
    }
    if(pJson.isMember("kind"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["kind"].isNull())
        {
            kind_=std::make_shared<std::string>(pJson["kind"].asString());
        }
    }
}

void TaskDependency::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dependsOnId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            kind_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void TaskDependency::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("task_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson["task_id"].asString());
        }
    }
    if(pJson.isMember("depends_on_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["depends_on_id"].isNull())
        {
            dependsOnId_=std::make_shared<std::string>(pJson["depends_on_id"].asString());
        }
    }
    if(pJson.isMember("kind"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["kind"].isNull())
        {
            kind_=std::make_shared<std::string>(pJson["kind"].asString());
        }
    }
}

const std::string &TaskDependency::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TaskDependency::getId() const noexcept
{
    return id_;
}
void TaskDependency::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void TaskDependency::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename TaskDependency::PrimaryKeyType & TaskDependency::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &TaskDependency::getValueOfTaskId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(taskId_)
        return *taskId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TaskDependency::getTaskId() const noexcept
{
    return taskId_;
}
void TaskDependency::setTaskId(const std::string &pTaskId) noexcept
{
    taskId_ = std::make_shared<std::string>(pTaskId);
    dirtyFlag_[1] = true;
}
void TaskDependency::setTaskId(std::string &&pTaskId) noexcept
{
    taskId_ = std::make_shared<std::string>(std::move(pTaskId));
    dirtyFlag_[1] = true;
}

const std::string &TaskDependency::getValueOfDependsOnId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(dependsOnId_)
        return *dependsOnId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TaskDependency::getDependsOnId() const noexcept
{
    return dependsOnId_;
}
void TaskDependency::setDependsOnId(const std::string &pDependsOnId) noexcept
{
    dependsOnId_ = std::make_shared<std::string>(pDependsOnId);
    dirtyFlag_[2] = true;
}
void TaskDependency::setDependsOnId(std::string &&pDependsOnId) noexcept
{
    dependsOnId_ = std::make_shared<std::string>(std::move(pDependsOnId));
    dirtyFlag_[2] = true;
}

const std::string &TaskDependency::getValueOfKind() const noexcept
{
    static const std::string defaultValue = std::string();
    if(kind_)
        return *kind_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TaskDependency::getKind() const noexcept
{
    return kind_;
}
void TaskDependency::setKind(const std::string &pKind) noexcept
{
    kind_ = std::make_shared<std::string>(pKind);
    dirtyFlag_[3] = true;
}
void TaskDependency::setKind(std::string &&pKind) noexcept
{
    kind_ = std::make_shared<std::string>(std::move(pKind));
    dirtyFlag_[3] = true;
}
void TaskDependency::setKindToNull() noexcept
{
    kind_.reset();
    dirtyFlag_[3] = true;
}

void TaskDependency::updateId(const uint64_t id)
{
}

const std::vector<std::string> &TaskDependency::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "task_id",
        "depends_on_id",
        "kind"
    };
    return inCols;
}

void TaskDependency::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTaskId())
        {
            binder << getValueOfTaskId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDependsOnId())
        {
            binder << getValueOfDependsOnId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getKind())
        {
            binder << getValueOfKind();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TaskDependency::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void TaskDependency::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTaskId())
        {
            binder << getValueOfTaskId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDependsOnId())
        {
            binder << getValueOfDependsOnId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getKind())
        {
            binder << getValueOfKind();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TaskDependency::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTaskId())
    {
        ret["task_id"]=getValueOfTaskId();
    }
    else
    {
        ret["task_id"]=Json::Value();
    }
    if(getDependsOnId())
    {
        ret["depends_on_id"]=getValueOfDependsOnId();
    }
    else
    {
        ret["depends_on_id"]=Json::Value();
    }
    if(getKind())
    {
        ret["kind"]=getValueOfKind();
    }
    else
    {
        ret["kind"]=Json::Value();
    }
    return ret;
}

Json::Value TaskDependency::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTaskId())
            {
                ret[pMasqueradingVector[1]]=getValueOfTaskId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDependsOnId())
            {
                ret[pMasqueradingVector[2]]=getValueOfDependsOnId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getKind())
            {
                ret[pMasqueradingVector[3]]=getValueOfKind();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTaskId())
    {
        ret["task_id"]=getValueOfTaskId();
    }
    else
    {
        ret["task_id"]=Json::Value();
    }
    if(getDependsOnId())
    {
        ret["depends_on_id"]=getValueOfDependsOnId();
    }
    else
    {
        ret["depends_on_id"]=Json::Value();
    }
    if(getKind())
    {
        ret["kind"]=getValueOfKind();
    }
    else
    {
        ret["kind"]=Json::Value();
    }
    return ret;
}

bool TaskDependency::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("task_id"))
    {
        if(!validJsonOfField(1, "task_id", pJson["task_id"], err, true))
            return false;
    }
    else
    {
        err="The task_id column cannot be null";
        return false;
    }
    if(pJson.isMember("depends_on_id"))
    {
        if(!validJsonOfField(2, "depends_on_id", pJson["depends_on_id"], err, true))
            return false;
    }
    else
    {
        err="The depends_on_id column cannot be null";
        return false;
    }
    if(pJson.isMember("kind"))
    {
        if(!validJsonOfField(3, "kind", pJson["kind"], err, true))
            return false;
    }
    return true;
}
bool TaskDependency::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TaskDependency::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("task_id"))
    {
        if(!validJsonOfField(1, "task_id", pJson["task_id"], err, false))
            return false;
    }
    if(pJson.isMember("depends_on_id"))
    {
        if(!validJsonOfField(2, "depends_on_id", pJson["depends_on_id"], err, false))
            return false;
    }
    if(pJson.isMember("kind"))
    {
        if(!validJsonOfField(3, "kind", pJson["kind"], err, false))
            return false;
    }
    return true;
}
bool TaskDependency::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TaskDependency::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
