/**
 *
 *  DelegationPermission.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "DelegationPermission.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::project_calendar;

const std::string DelegationPermission::Cols::_id = "\"id\"";
const std::string DelegationPermission::Cols::_delegation_id = "\"delegation_id\"";
const std::string DelegationPermission::Cols::_permission_key = "\"permission_key\"";
const std::string DelegationPermission::Cols::_allow = "\"allow\"";
const std::string DelegationPermission::primaryKeyName = "id";
const bool DelegationPermission::hasPrimaryKey = true;
const std::string DelegationPermission::tableName = "\"delegation_permission\"";

const std::vector<typename DelegationPermission::MetaData> DelegationPermission::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"delegation_id","std::string","uuid",0,0,0,1},
{"permission_key","std::string","text",0,0,0,1},
{"allow","bool","boolean",1,0,0,0}
};
const std::string &DelegationPermission::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
DelegationPermission::DelegationPermission(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["delegation_id"].isNull())
        {
            delegationId_=std::make_shared<std::string>(r["delegation_id"].as<std::string>());
        }
        if(!r["permission_key"].isNull())
        {
            permissionKey_=std::make_shared<std::string>(r["permission_key"].as<std::string>());
        }
        if(!r["allow"].isNull())
        {
            allow_=std::make_shared<bool>(r["allow"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            delegationId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            permissionKey_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            allow_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

DelegationPermission::DelegationPermission(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            delegationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            permissionKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            allow_=std::make_shared<bool>(pJson[pMasqueradingVector[3]].asBool());
        }
    }
}

DelegationPermission::DelegationPermission(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("delegation_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["delegation_id"].isNull())
        {
            delegationId_=std::make_shared<std::string>(pJson["delegation_id"].asString());
        }
    }
    if(pJson.isMember("permission_key"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["permission_key"].isNull())
        {
            permissionKey_=std::make_shared<std::string>(pJson["permission_key"].asString());
        }
    }
    if(pJson.isMember("allow"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["allow"].isNull())
        {
            allow_=std::make_shared<bool>(pJson["allow"].asBool());
        }
    }
}

void DelegationPermission::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            delegationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            permissionKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            allow_=std::make_shared<bool>(pJson[pMasqueradingVector[3]].asBool());
        }
    }
}

void DelegationPermission::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("delegation_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["delegation_id"].isNull())
        {
            delegationId_=std::make_shared<std::string>(pJson["delegation_id"].asString());
        }
    }
    if(pJson.isMember("permission_key"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["permission_key"].isNull())
        {
            permissionKey_=std::make_shared<std::string>(pJson["permission_key"].asString());
        }
    }
    if(pJson.isMember("allow"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["allow"].isNull())
        {
            allow_=std::make_shared<bool>(pJson["allow"].asBool());
        }
    }
}

const std::string &DelegationPermission::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &DelegationPermission::getId() const noexcept
{
    return id_;
}
void DelegationPermission::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void DelegationPermission::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename DelegationPermission::PrimaryKeyType & DelegationPermission::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &DelegationPermission::getValueOfDelegationId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(delegationId_)
        return *delegationId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &DelegationPermission::getDelegationId() const noexcept
{
    return delegationId_;
}
void DelegationPermission::setDelegationId(const std::string &pDelegationId) noexcept
{
    delegationId_ = std::make_shared<std::string>(pDelegationId);
    dirtyFlag_[1] = true;
}
void DelegationPermission::setDelegationId(std::string &&pDelegationId) noexcept
{
    delegationId_ = std::make_shared<std::string>(std::move(pDelegationId));
    dirtyFlag_[1] = true;
}

const std::string &DelegationPermission::getValueOfPermissionKey() const noexcept
{
    static const std::string defaultValue = std::string();
    if(permissionKey_)
        return *permissionKey_;
    return defaultValue;
}
const std::shared_ptr<std::string> &DelegationPermission::getPermissionKey() const noexcept
{
    return permissionKey_;
}
void DelegationPermission::setPermissionKey(const std::string &pPermissionKey) noexcept
{
    permissionKey_ = std::make_shared<std::string>(pPermissionKey);
    dirtyFlag_[2] = true;
}
void DelegationPermission::setPermissionKey(std::string &&pPermissionKey) noexcept
{
    permissionKey_ = std::make_shared<std::string>(std::move(pPermissionKey));
    dirtyFlag_[2] = true;
}

const bool &DelegationPermission::getValueOfAllow() const noexcept
{
    static const bool defaultValue = bool();
    if(allow_)
        return *allow_;
    return defaultValue;
}
const std::shared_ptr<bool> &DelegationPermission::getAllow() const noexcept
{
    return allow_;
}
void DelegationPermission::setAllow(const bool &pAllow) noexcept
{
    allow_ = std::make_shared<bool>(pAllow);
    dirtyFlag_[3] = true;
}
void DelegationPermission::setAllowToNull() noexcept
{
    allow_.reset();
    dirtyFlag_[3] = true;
}

void DelegationPermission::updateId(const uint64_t id)
{
}

const std::vector<std::string> &DelegationPermission::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "delegation_id",
        "permission_key",
        "allow"
    };
    return inCols;
}

void DelegationPermission::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getDelegationId())
        {
            binder << getValueOfDelegationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPermissionKey())
        {
            binder << getValueOfPermissionKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAllow())
        {
            binder << getValueOfAllow();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> DelegationPermission::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void DelegationPermission::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getDelegationId())
        {
            binder << getValueOfDelegationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPermissionKey())
        {
            binder << getValueOfPermissionKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAllow())
        {
            binder << getValueOfAllow();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value DelegationPermission::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDelegationId())
    {
        ret["delegation_id"]=getValueOfDelegationId();
    }
    else
    {
        ret["delegation_id"]=Json::Value();
    }
    if(getPermissionKey())
    {
        ret["permission_key"]=getValueOfPermissionKey();
    }
    else
    {
        ret["permission_key"]=Json::Value();
    }
    if(getAllow())
    {
        ret["allow"]=getValueOfAllow();
    }
    else
    {
        ret["allow"]=Json::Value();
    }
    return ret;
}

Json::Value DelegationPermission::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getDelegationId())
            {
                ret[pMasqueradingVector[1]]=getValueOfDelegationId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPermissionKey())
            {
                ret[pMasqueradingVector[2]]=getValueOfPermissionKey();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getAllow())
            {
                ret[pMasqueradingVector[3]]=getValueOfAllow();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDelegationId())
    {
        ret["delegation_id"]=getValueOfDelegationId();
    }
    else
    {
        ret["delegation_id"]=Json::Value();
    }
    if(getPermissionKey())
    {
        ret["permission_key"]=getValueOfPermissionKey();
    }
    else
    {
        ret["permission_key"]=Json::Value();
    }
    if(getAllow())
    {
        ret["allow"]=getValueOfAllow();
    }
    else
    {
        ret["allow"]=Json::Value();
    }
    return ret;
}

bool DelegationPermission::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("delegation_id"))
    {
        if(!validJsonOfField(1, "delegation_id", pJson["delegation_id"], err, true))
            return false;
    }
    else
    {
        err="The delegation_id column cannot be null";
        return false;
    }
    if(pJson.isMember("permission_key"))
    {
        if(!validJsonOfField(2, "permission_key", pJson["permission_key"], err, true))
            return false;
    }
    else
    {
        err="The permission_key column cannot be null";
        return false;
    }
    if(pJson.isMember("allow"))
    {
        if(!validJsonOfField(3, "allow", pJson["allow"], err, true))
            return false;
    }
    return true;
}
bool DelegationPermission::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                              const std::vector<std::string> &pMasqueradingVector,
                                                              std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool DelegationPermission::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("delegation_id"))
    {
        if(!validJsonOfField(1, "delegation_id", pJson["delegation_id"], err, false))
            return false;
    }
    if(pJson.isMember("permission_key"))
    {
        if(!validJsonOfField(2, "permission_key", pJson["permission_key"], err, false))
            return false;
    }
    if(pJson.isMember("allow"))
    {
        if(!validJsonOfField(3, "allow", pJson["allow"], err, false))
            return false;
    }
    return true;
}
bool DelegationPermission::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool DelegationPermission::validJsonOfField(size_t index,
                                            const std::string &fieldName,
                                            const Json::Value &pJson,
                                            std::string &err,
                                            bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
